[package]
name = "shell"
version = "0.1.0"
edition = "2021"
authors = [" Gabriel Ferrer gjf2a Ian Campbell ianc02"]





# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramdisk = {git = "https://github.com/gjf2a/ramdisk"}